Various integration test fixes (#984)
Various integration test fixes

SUMMARY

Updates the version of Python used by lambda in the lambda_alias, lambda_policy and aws_secret integration tests
Updates the version of NodeJS used by the lambda in the lamba integration tests
Adds a retry to the s3_bucket_notification tests, permissions are sometimes a little slow to update
Cleans up Snapshots from rds_instance integration tests
Disables broken WAFv2 integration test (#985)

Fixes: #976
ISSUE TYPE

Bugfix Pull Request

COMPONENT NAME
aws_secret
lambda
lambda_alias
lambda_policy
rds_policy
s3_bucket_notification
wafv2
ADDITIONAL INFORMATION
Amazon appear to have dropped support for creating Python2.7 lambdas:
botocore.errorfactory.InvalidParameterValueException: An error occurred (InvalidParameterValueException) when calling the CreateFunction operation: The runtime parameter of python2.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (python3.9) while creating or updating functions.

Reviewed-by: Alina Buzachis <None>