ec2_vpc_vpn - fix exception when running in check mode without tags set (#1242)
ec2_vpc_vpn - fix exception when running in check mode without tags set

SUMMARY

Rename ec2_vpc_vpn_info tests to ec2_vpc_vpn so we have baseline testing for VPNs (keep ec2_vpc_vpn_info as an alias)
fix exception when run in check mode without tags set.

ISSUE TYPE

Bugfix Pull Request

COMPONENT NAME
ec2_vpc_vpn
ADDITIONAL INFORMATION
TASK [ec2_vpc_vpn : (check) No change to tags without setting tags] ************
task path: /root/ansible_collections/community/aws/tests/output/.tmp/integration/ec2_vpc_vpn-oywt620e-ÅÑŚÌβŁÈ/tests/integration/targets/ec2_vpc_vpn/tasks/tags.yml:248
Using module file /root/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py
Pipelining is enabled.
<testhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<testhost> EXEC /bin/sh -c 'ANSIBLE_DEBUG_BOTOCORE_LOGS=True /usr/bin/python3.10 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "<stdin>", line 121, in <module>
  File "<stdin>", line 113, in _ansiballz_main
  File "<stdin>", line 61, in invoke_module
  File "/usr/lib/python3.10/runpy.py", line 209, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py", line 808, in <module>
  File "/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py", line 795, in main
  File "/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py", line 714, in ensure_present
  File "/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py", line 661, in get_check_mode_results
AttributeError: 'NoneType' object has no attribute 'keys'
fatal: [testhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"<stdin>\", line 121, in <module>\n  File \"<stdin>\", line 113, in _ansiballz_main\n  File \"<stdin>\", line 61, in invoke_module\n  File \"/usr/lib/python3.10/runpy.py\", line 209, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.10/runpy.py\", line 96, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py\", line 808, in <module>\n  File \"/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py\", line 795, in main\n  File \"/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py\", line 714, in ensure_present\n  File \"/tmp/ansible_ec2_vpc_vpn_payload_0zo_xg79/ansible_ec2_vpc_vpn_payload.zip/ansible_collections/community/aws/plugins/modules/ec2_vpc_vpn.py\", line 661, in get_check_mode_results\nAttributeError: 'NoneType' object has no attribute 'keys'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

Reviewed-by: Alina Buzachis <None>