Add ResourceType on ec2 snapshot copy (#1419)
Add ResourceType on ec2 snapshot copy

SUMMARY
Fixes this issue that shows up when tags are specified:
An error occurred waiting for the snapshot to become available.: An
error occurred (InvalidParameterValue) when calling the CopySnapshot
operation: Tag specification resource type must have a value

ISSUE TYPE

Bugfix Pull Request

COMPONENT NAME
ec2_snapshot_copy
ADDITIONAL INFORMATION

# before

botocore.exceptions.ClientError: An error occurred (InvalidParameterValue) when calling the CopySnapshot operation: Tag specification resource type must have a value
fatal: [localhost]: FAILED! => {
    "boto3_version": "1.24.57",
    "botocore_version": "1.27.58",
    "changed": false,
    "error": {
        "code": "InvalidParameterValue",
        "message": "Tag specification resource type must have a value"
    },
....

# after  (no error message)

changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
.....

Reviewed-by: Mark Chappell <None>
Reviewed-by: Colby Shores <coleshores@gmail.com>
Reviewed-by: None <None>
(cherry picked from commit fad358924d91150b6278a7832c2f2028d588bd44)