backport-4: Minor fixups (#1328) (#1393)
backport-4: Minor fixups (#1328)

forgotten backport-4 breaks ecs_service  in 4.1.0
after it's merged, 4.1.1 must be released asap
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1659604767.311191-146-86085088410654/AnsiballZ_ecs_service.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1659604767.311191-146-86085088410654/AnsiballZ_ecs_service.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1659604767.311191-146-86085088410654/AnsiballZ_ecs_service.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.aws.plugins.modules.ecs_service', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_ecs_service_payload_jubeafm6/ansible_ecs_service_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_service.py", line 1134, in <module>
  File "/tmp/ansible_ecs_service_payload_jubeafm6/ansible_ecs_service_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_service.py", line 969, in main
  File "/tmp/ansible_ecs_service_payload_jubeafm6/ansible_ecs_service_payload.zip/ansible_collections/community/aws/plugins/modules/ecs_service.py", line 733, in is_matching_service
KeyError: 'deploymentController'

ecs_service - Minor fixups
SUMMARY
Bad rebase resulted in a duplicated parameter
Fixup "changed" after adding initial support for tags
ISSUE TYPE
Feature Pull Request
COMPONENT NAME
ecs_service
ADDITIONAL INFORMATION
Bugs aren't in a released version yet, no need for changelog
Reviewed-by: Joseph Torcasso 
SUMMARY


ISSUE TYPE


Bugfix Pull Request
Docs Pull Request
Feature Pull Request
New Module Pull Request

COMPONENT NAME

ADDITIONAL INFORMATION

Reviewed-by: Mark Chappell <None>