incr version added (#1043)
eks_fargate_profile: incr version added

SUMMARY
CI is failing for stable-3  branch

NotImplementedError: Waiter fargate_profile_active could not be found for client <class 'botocore.client.EKS'>.


Possibly because the boto3 version in the main branch is higher as in the stable-3 branch.
It's still possible to backport this for the next 3.3.0 release. The integration test must install a higher boto3 version.
ISSUE TYPE


Docs Pull Request

COMPONENT NAME
eks_fargate_profile

Reviewed-by: Mark Chappell <None>
Reviewed-by: Mark Woolley <mw@marknet15.com>